open Ctypes

val c_PARAM_MASK : int32
val c_PARAM_STATIC_STRINGS : int32
val c_PARAM_USER_SHIFT : int32
(*DEPRECATED : Parameter*)
val c_SIGNAL_FLAGS_MASK : int32
val c_SIGNAL_MATCH_MASK : int32
val c_TYPE_FLAG_RESERVED_ID_BIT : Unsigned.uint64
val c_TYPE_FUNDAMENTAL_MAX : int32
val c_TYPE_FUNDAMENTAL_SHIFT : int32
val c_TYPE_RESERVED_BSE_FIRST : int32
val c_TYPE_RESERVED_BSE_LAST : int32
val c_TYPE_RESERVED_GLIB_FIRST : int32
val c_TYPE_RESERVED_GLIB_LAST : int32
val c_TYPE_RESERVED_USER_FIRST : int32
(*DEPRECATED : TypeDebugFlags*)
val c_VALUE_COLLECT_FORMAT_MAX_LENGTH : int32
val c_VALUE_NOCOPY_CONTENTS : int32
